// Generated by Wrangler on Wed Apr 24 2024 14:13:08 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
	AUTH_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	DB: D1Database;
}
